# Gradle 配置
# 设置 gradle 命令默认使用的内存,可被用户或命令行参数覆盖
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment 参数名映射(改善反编译源码的可读性,可选)
# 详情见: https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# 最新版本见: https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13

# 环境属性
# 最新版本见: https://projects.neoforged.net/neoforged/neoforge
# Minecraft 版本必须与 NeoForge 版本对应才能拿到有效构件
minecraft_version=1.21.1
# Minecraft 版本范围,可使用任意正式版本作为边界
# 快照、预发布版和候选版不保证能正确排序(不符合标准版本号约定)
minecraft_version_range=[1.21.1,)
# NeoForge 版本必须与 Minecraft 版本对应才能拿到有效构件
neo_version=21.1.250
# 加载器版本范围只能使用 FML 主版本作为边界
loader_version_range=[1,)

## 模组属性
# 模组唯一标识。必须小写英文,符合正则 [a-z][a-z0-9_]{1,63}
# 必须与主类 @Mod 注解中的字符串常量一致
mod_id=mod_scan_trans_lib
# 模组可读名称
mod_name=Mod Scan Translation Support Library
# 模组协议,见 https://choosealicense.com/
mod_license=MIT
# 模组版本,见 https://semver.org/
mod_version=1.0.0
# 模组 group id(发布到 Maven 仓库时才重要)
# 应与模组源码的基础包名一致
mod_group_id=com.modscantrans
